# Generated by Django 4.2.3 on 2023-11-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('slug', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'game_game',
            },
        ),
    ]
